# Generated by Django 4.1.2 on 2022-11-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=265)),
                ('buildings', models.CharField(max_length=265)),
                ('unitTypes', models.CharField(max_length=265)),
                ('dimensions', models.CharField(max_length=265)),
                ('priceRange', models.IntegerField(max_length=265)),
                ('amenity', models.CharField(max_length=265)),
            ],
        ),
    ]
