# Generated by Django 4.1.2 on 2022-11-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentnow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='priceRange',
            field=models.IntegerField(),
        ),
    ]
