# Generated by Django 4.1.2 on 2022-11-02 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentnow', '0002_units_slug_alter_units_pricerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='units',
            name='userType',
            field=models.CharField(choices=[('Business User', 'BusinessUser'), ('Personal User', 'Sophomore')], default='Business User', max_length=265),
        ),
    ]
