# Generated by Django 4.1.2 on 2022-11-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentnow', '0003_units_date_units_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='userType',
            field=models.CharField(choices=[('Business User', 'BusinessUser'), ('Personal User', 'Personal User')], default='Business User', max_length=265),
        ),
    ]
